# Generated by Django 5.0 on 2023-12-30 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0009_rename_date_added_date_added_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='date_added',
            name='Song_Added',
            field=models.CharField(default='YourDefaultValueHere', max_length=255),
        ),
    ]
