# Generated by Django 5.0 on 2023-12-30 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0010_date_added_song_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date_added',
            name='Deadline',
        ),
    ]
