# Generated by Django 5.0 on 2023-12-30 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0011_remove_date_added_deadline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='FirstName',
            new_name='Artist',
        ),
        migrations.RenameField(
            model_name='title',
            old_name='LastName',
            new_name='Duration',
        ),
        migrations.RenameField(
            model_name='title',
            old_name='titleID',
            new_name='SongName',
        ),
        migrations.RemoveField(
            model_name='title',
            name='Email',
        ),
    ]
